version: '3.6'

services:
  backend:
    image: dev/happynanny_backend
    ports:
      - "9900:9900"
    environment:
      ENV: development

  frontend:
    build:
      target: dev-stage
    image: dev/happynanny_frontend
    ports:
      - "8080:8080"
    # uncomment for hot reload
    # volumes: 
    #   - ./frontend/src:/app/src
    links:
      - backend
    environment:
      ENV: development

  reverseproxy:
    image: dev/happynanny_reverseproxy
    links:
      - frontend
      - backend
    environment:
      ENV: development
