version: '3.6'

services:
  backend:
    build:
      target: dev-stage
    image: dev/happynanny_backend
    ports:
      - "9900:9900"
    volumes: 
      - ./backend/src:/app/src
    environment:
      ENV: development
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}


  frontend:
    build:
      target: dev-stage
    image: dev/happynanny_frontend
    ports:
      - "8080:8080"
    volumes: 
      - ./frontend/src:/app/src
    links:
      - backend
    environment:
      ENV: development

  reverseproxy:
    image: dev/happynanny_reverseproxy
    links:
      - frontend
      - backend
    environment:
      ENV: development
