version: '3.6'

services:
  backend:
    environment:
      ENV: development

  frontend:
    volumes: 
      - ./frontend/src:/app/src
    ports:
      - "8086:8086"
      - "3030:3030"
    links:
      - backend
    environment:
      ENV: development

  reverseproxy:
    links:
      - frontend
      - backend
    environment:
      ENV: development
