version: '3.6'

services:
  backend:
    environment:
      ENV: production

  frontend:
    build:
      target: production-stage
    environment:
      ENV: production

  reverseproxy:
    environment:
      ENV: production
